# Generated by Django 2.1.5 on 2019-02-08 19:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0004_auto_20190208_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024, verbose_name='description')),
                ('date', models.DateField(verbose_name='date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount')),
            ],
            options={
                'verbose_name': 'payment received from tenant',
                'verbose_name_plural': 'payments received from tenant',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('text', models.TextField(verbose_name='description')),
                ('read', models.BooleanField(default=False, verbose_name='mark as read')),
            ],
            options={
                'verbose_name': 'reminder',
                'verbose_name_plural': 'reminders',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('tenancy_begin_date', models.DateField(verbose_name='tenancy begin date')),
                ('tenancy_end_date', models.DateField(blank=True, null=True, verbose_name='tenancy end date')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, help_text='A sum of money asked to tenant on day 1. It is payed back in full on the final day of the tenancy', max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='deposit')),
                ('contact_info', models.TextField(blank=True, verbose_name='contact info')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='property.Property', verbose_name='property')),
            ],
            options={
                'verbose_name': 'tenant',
                'verbose_name_plural': 'tenants',
                'ordering': ['tenancy_end_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TenantFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('file', models.FileField(upload_to='tenant', verbose_name='file')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.Tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
            },
        ),
        migrations.AddField(
            model_name='reminder',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.Tenant', verbose_name='tenant'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.Tenant', verbose_name='tenant'),
        ),
    ]
