# Generated by Django 2.1.5 on 2019-02-08 20:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, help_text='date at which the rent generation should stop (non-inclusive)', null=True, verbose_name='end date')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='monthly rent')),
                ('provision', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='monthly provision')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.Tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'rent revision',
                'verbose_name_plural': 'rent revisions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AlterField(
            model_name='tenantfile',
            name='file',
            field=models.FileField(upload_to='tenant/docs', verbose_name='file'),
        ),
    ]
