# Generated by Django 2.1.5 on 2019-02-11 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_discount_fee_refund'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.Fee', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TenantReminders',
            fields=[
            ],
            options={
                'verbose_name': 'tenant reminder list',
                'verbose_name_plural': 'tenants reminder lists',
                'proxy': True,
                'indexes': [],
            },
            bases=('tenants.tenant',),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.Tenant', verbose_name='tenant'),
        ),
    ]
