# Generated by Django 2.1.5 on 2019-02-08 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='prop_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='property.PropertyType'),
            preserve_default=False,
        ),
    ]
