# Generated by Django 2.1.5 on 2019-02-08 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_prop_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('file', models.FileField(upload_to='property', verbose_name='file')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property', verbose_name='property')),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
            },
        ),
    ]
