# Generated by Django 2.1.5 on 2019-02-09 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20190208_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
